export default <{ [key: string]: string }>{
  'administrator': 'Administrator',
  'createInstantInvite': 'Create Instant Invite',
  'kickMembers': 'Kick Members',
  'banMembers': 'Ban Members',
  'manageChannels': 'Manage Channels',
  'manageGuild': 'Manage Server',
  'addReactions': 'Add Reactions',
  'viewAuditLogs': 'View Audit Log',
  'voicePrioritySpeaker': 'Priority Speaker',
  'stream': 'Video',
  'readMessages': 'View Channels',
  'sendMessages': 'Send Messages',
  'sendTTSMessages': 'Send TTS Messages',
  'manageMessages': 'Manage Messages',
  'embedLinks': 'Embed Links',
  'attachFiles': 'Attach Files',
  'readMessageHistory': 'Read Message History',
  'mentionEveryone': 'Mention Everyone',
  'externalEmojis': 'Use External Emojis',
  'viewGuildInsights': 'View Guild Insights',
  'voiceConnect': 'Connect',
  'voiceSpeak': 'Speak',
  'voiceMuteMembers': 'Mute Members',
  'voiceDeafenMembers': 'Deafen Members',
  'voiceMoveMembers': 'Use (Move) Members',
  'voiceUseVAD': 'Use Voice Activity',
  'changeNickname': 'Change Nickname',
  'manageNicknames': 'Manage Nicknames',
  'manageRoles': 'Manage Roles',
  'manageWebhooks': 'Manage Webhooks',
  'manageEmojis': 'Manage Emojis'
};
